binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: cryptohash-cryptoapi 0.1.3

  Hackage:  fb 1.0.10

  Hackage:  yesod-fb 0.3.3

  Hackage: yesod-auth-fb 1.6.6

'
ghc-args:
- -fdefer-type-errors
excluded-modules: []
